<?php

namespace MatiereBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends EntityRepository
{
    public function supprimerMatiere()
    {
        $conn = $this->getEntityManager()->getConnection();
        $b=$_GET['idMatiere'];
        $sql = "
        
        DELETE FROM Matiere 
WHERE id_matiere= $b
        ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();

    }
}
