<?php

namespace ClubBundle\Repository;

/**
 * DemandeClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeClubRepository extends \Doctrine\ORM\EntityRepository
{
}
