<?php

namespace ReclamationBundle\Repository;


/**
 * reclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamationRepository extends \Doctrine\ORM\EntityRepository
{


    public function repondre($id,$reponse){
        $query = $this->getEntityManager()
            ->createQuery(" UPDATE ReclamationBundle:reclamation e SET e.reponse=:reponse  where e.id=:id ")
            ->setParameter('id', $id)
            ->setParameter('reponse',$reponse);
        return $query->getResult();
    }


    public function Tri(){

        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery(

            "SELECT q  FROM ReclamationBundle:reclamation q order by q.status ASC");
        $result= $query->execute();
        return $result;
    }



    public function UserReclamation($id){

        $query = $this->getEntityManager()
            ->createQuery("SELECT a FROM ReclamationBundle:Reclamation a
      where a.idUser='$id'");

        return $query->getResult();
    }
    public function countReclamation($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT  COUNT(a) FROM ReclamationBundle:Reclamation a
      where a.idUser='$id'");
             return $query->getResult();
    }




}
