<?php

namespace StageBundle\Repository;

use Doctrine\ORM\EntityRepository;




/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends EntityRepository
{
    public function supprimerStage()
    {
        $conn = $this->getEntityManager()->getConnection();
$b=$_GET['idStage'];
        $sql = "
        
        DELETE FROM Stage 
WHERE id_stage= $b
        ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();

    }

    public function PostulerStage()
    {


        $conn = $this->getEntityManager()->getConnection();
        $user1= $this->getUser()->getId();
        var_dump($user1);

        $b=$_GET['idStageaffect'];
        $sql = "INSERT INTO Affectation 
( `id_stage`, `id_user`, `postuler`) VALUES 
(  $b , 12 ,  '\"nonvalid\"' );

        
        ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();


    }
    public function AffecterStage()
    {


        $conn = $this->getEntityManager()->getConnection();
        $b=$_GET['idStageaffected'];
        $sqlu = "UPDATE Affectation SET postuler='\"valid\"' WHERE `id_user`= 12 and id_stage=$b  and postuler='\"nonvalid\"'";

        $sql = " UPDATE Stage SET capacite_max=capacite_max-1 WHERE id_stage=$b  ";

        $sqla ="DELETE FROM Stage WHERE capacite_max= 0";

        $stmt = $conn->prepare($sqlu);
        $stmtt = $conn->prepare($sql);
        $stmttt = $conn->prepare($sqla);

        $stmt->execute();
        $stmtt->execute();
        $stmttt->execute();

    }

}
