<?php

namespace SalleBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * SalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleRepository extends EntityRepository
{
    public function supprimerSalle()
    {
        $conn = $this->getEntityManager()->getConnection();
        $b=$_GET['idSalle'];
        $sql = "
        
        DELETE FROM Salle 
WHERE id_salle= $b
        ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();

    }
}
