esprit_api_homepage:
    path:     /
    defaults: { _controller: EspritApiBundle:Default:index }

all:
    path:  /tasks/all
    defaults: { _controller: EspritApiBundle:Default:all }

all1:
    path:  /tasks/all1
    defaults: { _controller: EspritApiBundle:Default:all1 }

find_task:
    path: /tasks/find
    defaults: { _controller: EspritApiBundle:Default:find111 }

find_By_Id:
    path: /tasks/findByCin/{cin}
    defaults: { _controller: EspritApiBundle:Default:findByCin }

create_task:
    path:  /tasks/new
    defaults: { _controller: EspritApiBundle:Default:new }
    
create_task1:
    path:  /tasks/new1
    defaults: { _controller: EspritApiBundle:Default:new1 }

majeur:
    path:  /tasks/majeur
    defaults: { _controller: EspritApiBundle:Default:stat }


create_User:
    path:  /tasks/newUser
    defaults: { _controller: EspritApiBundle:Default:newUser }

login_User:
    path:  /tasks/login
    defaults: { _controller: EspritApiBundle:Default:login }