Rmatiere_matiere:
    resource: "@MatiereBundle/Resources/config/routing/matiere.yml"
    prefix:   /matiere

matiere_homepage:
    path:     /
    defaults: { _controller: MatiereBundle:Default:index }
