


app:
    resource: "@AppBundle/Controller/"
    type:     annotation


user_user:
    resource: "@UserUserBundle/Resources/config/routing.yml"
    prefix:   /User

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /


forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /




