

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user
seance:
    resource: "@SeanceBundle/Resources/config/routing.yml"
    prefix:   /seance






app:
    resource: "@AppBundle/Controller/"
    type:     annotation

classe:
    resource: "@ClasseBundle/Resources/config/routing.yml"
    prefix:   /classe

salle:
    resource: "@SalleBundle/Resources/config/routing.yml"
    prefix:   /salle

matiere:
    resource: "@MatiereBundle/Resources/config/routing.yml"
    prefix:   /matiere
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

