evaliat:
    resource: "@EvaliatBundle/Resources/config/routing.yml"
    prefix:   /





fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

notes:
    resource: "@NotesBundle/Resources/config/routing.yml"
    prefix:   /note



app:
    resource: "@AppBundle/Controller/"
    type:     annotation

classe:
    resource: "@ClasseBundle/Resources/config/routing.yml"
    prefix:   /classe

salle:
    resource: "@SalleBundle/Resources/config/routing.yml"
    prefix:   /salle

matiere:
    resource: "@MatiereBundle/Resources/config/routing.yml"
    prefix:   /matiere


