type_stage:
    resource: "@TypeStageBundle/Resources/config/routing.yml"
    prefix:   /type_stage







app:
    resource: "@AppBundle/Controller/"
    type:     annotation

classe:
    resource: "@ClasseBundle/Resources/config/routing.yml"
    prefix:   /classe

salle:
    resource: "@SalleBundle/Resources/config/routing.yml"
    prefix:   /salle

matiere:
    resource: "@MatiereBundle/Resources/config/routing.yml"
    prefix:   /matiere

stage:
    resource: "@StageBundle/Resources/config/routing.yml"
    prefix:   /stage

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
user_user:
    resource: "@UserUserBundle/Resources/config/routing.yml"
    prefix:   /




