





app:
    resource: "@AppBundle/Controller/"
    type:     annotation

classe:
    resource: "@ClasseBundle/Resources/config/routing.yml"
    prefix:   /classe

salle:
    resource: "@SalleBundle/Resources/config/routing.yml"
    prefix:   /salle

matiere:
    resource: "@MatiereBundle/Resources/config/routing.yml"
    prefix:   /matiere
