
esprit_api:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix:   /api



calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /calendar


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

notes:
    resource: "@NotesBundle/Resources/config/routing.yml"
    prefix:   /note



app:
    resource: "@AppBundle/Controller/"
    type:     annotation

classe:
    resource: "@ClasseBundle/Resources/config/routing.yml"
    prefix:   /classe

salle:
    resource: "@SalleBundle/Resources/config/routing.yml"
    prefix:   /salle

matiere:
    resource: "@MatiereBundle/Resources/config/routing.yml"
    prefix:   /matiere


stage:
    resource: "@StageBundle/Resources/config/routing.yml"
    prefix:   /stage



forum:
    resource: "@ForumBundle/Resources/config/routing/question.yml"
    prefix:   /forum

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation




absence_employe:
    resource: "@AbsenceEmployeBundle/Resources/config/routing.yml"
    prefix:   /absenceemp

absence:
    resource: "@AbsenceBundle/Resources/config/routing.yml"
    prefix:   /absence


evaliat:
    resource: "@EvaliatBundle/Resources/config/routing.yml"
    prefix:   /evaluationn

type_stage:
    resource: "@TypeStageBundle/Resources/config/routing.yml"
    prefix:   /type_stage




user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user
seance:
    resource: "@SeanceBundle/Resources/config/routing.yml"
    prefix:   /seance



toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"