note_index:
    path:     /
    defaults: { _controller: "NotesBundle:Note:index" }
    methods:  GET

note_show:
    path:     /{idNote}/show
    defaults: { _controller: "NotesBundle:Note:show" }
    methods:  GET

note_new:
    path:     /new
    defaults: { _controller: "NotesBundle:Note:new" }
    methods:  [GET, POST]

note_edit:
    path:     /{idNote}/edit
    defaults: { _controller: "NotesBundle:Note:edit" }
    methods:  [GET, POST]

note_delete:
    path:     /{idNote}/delete
    defaults: { _controller: "NotesBundle:Note:delete" }
    methods:  DELETE







