<?php

namespace TypeStageBundle\Repository;

/**
 * TypeStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeStageRepository extends \Doctrine\ORM\EntityRepository
{
    public function supprimerTypeStage()
    {
        $conn = $this->getEntityManager()->getConnection();
        $b=$_GET['id'];
        $sql = "
        
        DELETE FROM type_stage 
WHERE id= $b
        ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();

    }
}
