<?php


namespace UserBundle\Repository;


/**
 * UserRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class UserRepository extends EntityRepository
{
    public function findAffect()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT a FROM UserBundle:User a WHERE a.roles Like '%\"ROLE_ETUDIANT\"%' AND a.idClasse=0 ");
        return $query->getResult();
    }
    public function findAffectclasse($idclass)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT COUNT(a) FROM UserBundle:User a WHERE  a.roles Like '%\"ROLE_ETUDIANT\"%' AND a.idClasse='$idclass' ");
        return $query->getResult();
    }
    public function editAffect($idclasse,$iduser)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = "
        UPDATE User
    SET id_classe = $idclasse
WHERE id = $iduser
       
        ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();

    }


}