seance_index:
    path:     /
    defaults: { _controller: "SeanceBundle:Seance:index" }
    methods: [GET, POST]

seance_show:
    path:     /{idSeance}/show
    defaults: { _controller: "SeanceBundle:Seance:show" }
    methods:  GET

seance_new:
    path:     /new
    defaults: { _controller: "SeanceBundle:Seance:new" }
    methods:  [GET, POST]

seance_edit:
    path:     /{idSeance}/edit
    defaults: { _controller: "SeanceBundle:Seance:edit" }
    methods:  [GET, POST]

seance_delete:
    path:     /{idSeance}/delete
    defaults: { _controller: "SeanceBundle:Seance:delete" }
    methods:  DELETE
