<?php

namespace ClasseBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends EntityRepository
{
    public function supprimerClasse()
    {
        $conn = $this->getEntityManager()->getConnection();
$b=$_GET['idClasse'];
        $sql = "
        
        DELETE FROM Classe 
WHERE id_classe= $b
        ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();

    }
}
