<?php

namespace SeanceBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends EntityRepository
{

    public function findOneByVerifClasse($idclass)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT COUNT(a) FROM SeanceBundle:Seance a WHERE a.idClasse='$idclass' ");
        return $query->getResult();
    }
    public function findOneByVerifMatiere($idmatiere)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT COUNT(a) FROM SeanceBundle:Seance a WHERE a.idMatiere='$idmatiere' ");
        return $query->getResult();
    }
    public function findOneByVerifSale($idsalle)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT COUNT(a) FROM SeanceBundle:Seance a WHERE a.idSalle='$idsalle' ");
        return $query->getResult();
    }
    public function supprimerSeance()
    {
        $conn = $this->getEntityManager()->getConnection();
        $b=$_GET['idSeance'];
        $sql = "
        
        DELETE FROM Seance 
WHERE id_seance= $b
        ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();

    }
}
