<?php

namespace ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function supprimerQuestion()
    {
        $conn = $this->getEntityManager()->getConnection();
        $b=$_GET['idQues'];
        $sql = "
        
        DELETE FROM Question 
WHERE id_ques= $b
        ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();

    }




}
