<?php

namespace AbsenceBundle\Repository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function count()
    {
        $query  = $this->getEntityManager()
        ->createQuery("SELECT COUNT(a) FROM AbsenceBundle:Absence a ");
        return $query->getResult();
    }
}
