<?php

namespace AbsenceBundle\Repository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function count($iduser)
    {
        $query  = $this->getEntityManager()
        ->createQuery("SELECT COUNT(a) FROM AbsenceBundle:Absence a where a.idEtudiant='$iduser' ");
        return $query->getResult();
    }
    public function absenceEtudiant($iduser)
    {
        $query  = $this->getEntityManager()
            ->createQuery("SELECT a FROM AbsenceBundle:Absence a where a.idEtudiant='$iduser' ");
        return $query->getResult();
    }
}
